/*
 * Migration status block (SKODA-603): the pilot migration status for people who don't read
 * the engineering tracker (docs/planning/skoda-m1-url-status.md).
 *
 * Authored as a config table on /drafts/migration-status:
 *   | Migration Status |                                   |
 *   | source           | /drafts/migration-status-data.json |
 * The sheet is generated by `npm run import:status -- --sheet <file>`
 * (tools/importer/m1-status.mjs, statusSheet in push/m1-status-lib.mjs): one row per page with
 * Type, Kind (page | alias), Title, Source, Migrated, Status (live | redirect | preview | held |
 * not live), QA, Note, Checked.
 *
 * Renders, answer first: a headline ("185 of 186 pages live"), one card per page type, the
 * exceptions in plain words, a page finder, then every page grouped by type in <details>. The
 * counts are derived from the rows, so the summary can't disagree with the list.
 */

import { readBlockConfig } from '../../scripts/aem.js';

const STATUS_LABELS = {
  live: 'Live',
  redirect: 'Redirects',
  preview: 'Preview only',
  held: 'Held',
  'not live': 'Not live',
};

// A redirect row is a reachable old address: it counts as live, as in the tracker.
const isLive = (row) => row.Status === 'live' || row.Status === 'redirect';

function el(tag, props = {}, ...children) {
  const node = document.createElement(tag);
  Object.entries(props).forEach(([key, value]) => {
    if (key === 'className') node.className = value;
    else node.setAttribute(key, value);
  });
  node.append(...children.filter((child) => child != null && child !== ''));
  return node;
}

function outLink(href, text, label) {
  return el('a', {
    href, target: '_blank', rel: 'noopener noreferrer', 'aria-label': `${label} (opens in a new tab)`,
  }, text);
}

function badge(status) {
  return el('span', { className: `migration-status-badge status-${status.replace(/\s+/g, '-')}` }, STATUS_LABELS[status] || status);
}

/** "2026-09-30 13:21 UTC" → "30 Sep 2026, 13:21 UTC"; anything else is shown as is. */
export function formatChecked(value) {
  const m = String(value || '').match(/^(\d{4})-(\d{2})-(\d{2}) (\d{2}:\d{2}) UTC$/);
  if (!m) return String(value || '');
  const month = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'][Number(m[2]) - 1];
  return `${Number(m[3])} ${month} ${m[1]}, ${m[4]} UTC`;
}

/** Page counts per type, in first-seen order; aliases are listed but not counted. */
export function summarize(rows) {
  const types = new Map();
  const total = { pages: 0, live: 0 };
  rows.forEach((row) => {
    if (!types.has(row.Type)) {
      types.set(row.Type, {
        type: row.Type, pages: 0, live: 0, rows: [],
      });
    }
    const t = types.get(row.Type);
    t.rows.push(row);
    if (row.Kind === 'alias') return;
    [t, total].forEach((acc) => {
      acc.pages += 1;
      if (isLive(row)) acc.live += 1;
    });
  });
  return { types: [...types.values()], total };
}

function typeCard({ type, pages, live }) {
  const bar = el('span', { className: 'migration-status-bar', 'aria-hidden': 'true' });
  bar.style.setProperty('--migration-status-share', pages ? live / pages : 0);
  return el(
    'li',
    { className: live === pages ? 'complete' : 'incomplete' },
    el('span', { className: 'migration-status-type' }, type),
    el('span', { className: 'migration-status-count' }, el('strong', {}, String(live)), ` of ${pages} live`),
    bar,
  );
}

function attention(rows) {
  // Most urgent first: held / not live, then preview, redirects, and live pages with a note.
  const rank = ['held', 'not live', 'preview', 'redirect', 'live'];
  const items = rows.filter((row) => row.Status !== 'live' || row.Note)
    .map((row, i) => ({ row, i }))
    .sort((a, b) => (rank.indexOf(a.row.Status) - rank.indexOf(b.row.Status)) || a.i - b.i)
    .map(({ row }) => row);
  if (!items.length) return null;
  const list = el('ul', { className: 'migration-status-attention' });
  items.forEach((row) => {
    list.append(el(
      'li',
      {},
      badge(row.Status),
      el('span', { className: 'migration-status-title' }, row.Title),
      row.Note ? el('span', { className: 'migration-status-note' }, row.Note) : null,
      el(
        'span',
        { className: 'migration-status-links' },
        outLink(row.Source, 'Source ↗', `${row.Title} on the source site`),
        outLink(row.Migrated, 'New ↗', `${row.Title} on the new site`),
      ),
    ));
  });
  return el('section', { 'aria-labelledby': 'migration-status-attention' }, el('h2', { id: 'migration-status-attention' }, 'Needs attention'), list);
}

function typeTable(group) {
  const tbody = el('tbody');
  group.rows.forEach((row) => {
    const tr = el(
      'tr',
      { 'data-search': `${row.Title} ${row.Source} ${row.Migrated}`.toLowerCase() },
      el('th', { scope: 'row' }, row.Title, row.Kind === 'alias' ? el('span', { className: 'migration-status-note' }, ' (old address)') : null),
      el('td', {}, badge(row.Status), row.Note ? el('span', { className: 'migration-status-note' }, row.Note) : null),
      el('td', {}, outLink(row.Source, 'Source ↗', `${row.Title} on the source site`)),
      el('td', {}, outLink(row.Migrated, 'New ↗', `${row.Title} on the new site`)),
    );
    tbody.append(tr);
  });
  const table = el(
    'table',
    {},
    el('caption', {}, `${group.type}: ${group.live} of ${group.pages} pages live`),
    el('thead', {}, el('tr', {}, ...['Page', 'Status', 'Source site', 'New site'].map((h) => el('th', { scope: 'col' }, h)))),
    tbody,
  );
  return el(
    'details',
    { className: 'migration-status-group' },
    el('summary', {}, el('span', {}, group.type), el('span', { className: 'migration-status-count' }, `${group.live} of ${group.pages} live`)),
    el('div', { className: 'migration-status-scroll' }, table),
  );
}

function finder(groups, status) {
  const input = el('input', {
    type: 'search', id: 'migration-status-find', placeholder: 'Page title or URL', autocomplete: 'off',
  });
  input.addEventListener('input', () => {
    const q = input.value.trim().toLowerCase();
    let hits = 0;
    groups.forEach((details) => {
      let groupHits = 0;
      details.querySelectorAll('tbody tr').forEach((tr) => {
        const match = !q || tr.dataset.search.includes(q);
        tr.hidden = !match;
        if (match) groupHits += 1;
      });
      details.hidden = !!q && !groupHits;
      if (q) details.open = groupHits > 0;
      hits += groupHits;
    });
    status.textContent = q ? `${hits} ${hits === 1 ? 'page' : 'pages'} found` : '';
  });
  return el(
    'div',
    { className: 'migration-status-finder' },
    el('label', { for: 'migration-status-find' }, 'Find a page'),
    input,
  );
}

export function render(block, rows) {
  const { types, total } = summarize(rows);
  const checked = formatChecked(rows[0] && rows[0].Checked);
  const counts = Object.keys(STATUS_LABELS)
    .map((s) => [s, rows.filter((r) => r.Kind !== 'alias' && r.Status === s).length])
    .filter(([, n]) => n);

  const head = el(
    'section',
    { className: 'migration-status-head' },
    el('p', { className: 'migration-status-headline' }, el('strong', {}, `${total.live} of ${total.pages}`), ' pilot pages are live'),
    checked ? el('p', { className: 'migration-status-checked' }, `Checked ${checked}`) : null,
    el('ul', { className: 'migration-status-legend', 'aria-label': 'Pages by status' }, ...counts.map(([s, n]) => el('li', {}, badge(s), ` ${n}`))),
  );
  const cards = el('ul', { className: 'migration-status-types', 'aria-label': 'Pages by type' }, ...types.map(typeCard));
  const groups = types.map(typeTable);
  const found = el('p', { className: 'migration-status-found', role: 'status' });
  block.replaceChildren(
    head,
    cards,
    attention(rows) || '',
    el(
      'section',
      { className: 'migration-status-all', 'aria-labelledby': 'migration-status-all' },
      el('h2', { id: 'migration-status-all' }, 'All pages'),
      finder(groups, found),
      found,
      ...groups,
    ),
  );
}

export default async function decorate(block) {
  const { source } = readBlockConfig(block);
  if (!source) {
    block.replaceChildren(el('p', {}, 'Migration status: no source sheet configured.'));
    return;
  }
  try {
    const url = new URL(source, window.location.href);
    url.searchParams.set('limit', '5000');
    const res = await fetch(url);
    if (!res.ok) throw new Error(`HTTP ${res.status}`);
    const { data = [] } = await res.json();
    render(block, data);
  } catch (e) {
    block.replaceChildren(el('p', {}, `Migration status could not be loaded (${e.message}).`));
  }
}
